name: Test

on: [push, pull_request]

jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Start Data Copy
        uses: ./
        with:
          datatemplatename: 'Tes Copy'
          apiToken: 'a39966d6-7d90-4661-bd9c-a0945c1854e7'